### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by Emilot** [jcorporation/ympd#3]
Great work!

Love the new GUI. Congrats :)

When i build with:
cmake .. -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_BUILD_TYPE=RELEASE

i get an 404 not found error when i run it with ./mympd -w80

When i build with:

cmake .. -DCMAKE_INSTALL_PREFIX:PATH=/usr

Plays fine, except of course the album covers.

Thank you JCorp excellent job. I hope you will keep it up and make it perfect!

**Comment by jcorporation** [comment]
Many thanks,

when you build with:
cmake .. -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_BUILD_TYPE=RELEASE
you must do a 
#make install
afterwards, because the document root is set to /usr/share/mympd/htdocs

Without -DCMAKE_BUILD_TYPE=RELEASE
the document root is set to /path/to/src/htdocs

Linking your mpd library in the htdocs directory should work in both scenarios.

I hope this helps

**Comment by Emilot** [comment]
Oh, perfect!

Thank you for the fast reply.

**Comment by jcorporation** [comment]
No problem
